import type { SimulatorDefinition } from "./types";

export const simulators: SimulatorDefinition[] = [
  {
    id: "photoelectric",
    name: "Photoelectric Effect",
    discipline: "Physics",
    domain: "Quantum",
    status: "live",
    summary: "Photon energy, threshold frequency, stopping potential.",
  },
  {
    id: "double-slit",
    name: "Double Slit",
    discipline: "Physics",
    domain: "Waves",
    status: "live",
    summary: "Interference, diffraction envelope, detector intensity.",
  },
  {
    id: "alcohol-oxidation",
    name: "Alcohol Oxidation",
    discipline: "Chemistry",
    domain: "Organic Chemistry",
    status: "live",
    summary: "Secondary alcohols, ketones, and acid-forming routes.",
  },
  {
    id: "acid-base-ph",
    name: "Acid-Base pH",
    discipline: "Chemistry",
    domain: "Analytical Chemistry",
    status: "live",
    summary: "Neutralization, equivalence point, logarithmic pH.",
  },
  {
    id: "solution-dilution",
    name: "Solution Dilution",
    discipline: "Chemistry",
    domain: "Analytical Chemistry",
    status: "live",
    summary: "Stock solutions, aliquots, final volume, and dilution factor.",
  },
  {
    id: "stoichiometry",
    name: "Stoichiometry",
    discipline: "Chemistry",
    domain: "General Chemistry",
    status: "live",
    summary: "Balanced mole ratios, limiting reactants, and product yield.",
  },
  {
    id: "ideal-gas-law",
    name: "Ideal Gas Law",
    discipline: "Chemistry",
    domain: "Physical Chemistry",
    status: "live",
    summary: "Pressure, volume, temperature, and amount in a piston.",
  },
  {
    id: "reaction-kinetics",
    name: "Reaction Kinetics",
    discipline: "Chemistry",
    domain: "Physical Chemistry",
    status: "live",
    summary: "First-order decay, half-life, rate constant, and product formation.",
  },
  {
    id: "sampling-lab",
    name: "Normal & t-Test Lab",
    discipline: "Math",
    domain: "Statistics",
    status: "live",
    summary: "Sampling distributions, standard error, t values.",
  },
  {
    id: "vector-addition",
    name: "Vector Addition",
    discipline: "Math",
    domain: "Foundations",
    status: "live",
    summary: "Components, magnitude, angle, resultant vector.",
  },
  {
    id: "linear-regression",
    name: "Linear Regression",
    discipline: "Math",
    domain: "Statistics",
    status: "live",
    summary: "Least-squares line, residuals, noise, and R Squared.",
  },
  {
    id: "pythagorean-theorem",
    name: "Pythagorean Theorem",
    discipline: "Math",
    domain: "Geometry",
    status: "live",
    summary: "Right triangles, square areas, and hypotenuse length.",
  },
  {
    id: "unit-circle",
    name: "Unit Circle",
    discipline: "Math",
    domain: "Trigonometry",
    status: "live",
    summary: "Sine, cosine, tangent, radians, and angle coordinates.",
  },
  {
    id: "binomial-distribution",
    name: "Binomial Distribution",
    discipline: "Math",
    domain: "Probability",
    status: "live",
    summary: "Repeated trials, exact probabilities, expected count, and spread.",
  },
  {
    id: "exponential-growth",
    name: "Exponential Growth",
    discipline: "Math",
    domain: "Functions",
    status: "live",
    summary: "Continuous growth, decay, multipliers, and doubling time.",
  },
  {
    id: "wave-superposition",
    name: "Wave Superposition",
    discipline: "Physics",
    domain: "Waves",
    status: "live",
    summary: "Amplitude, phase, frequency, summed wave.",
  },
  {
    id: "standing-wave",
    name: "Standing Wave On A String",
    discipline: "Physics",
    domain: "Waves",
    status: "live",
    summary: "Fixed-end harmonics, nodes, antinodes, and resonance.",
  },
  {
    id: "doppler-effect",
    name: "Doppler Effect",
    discipline: "Physics",
    domain: "Waves",
    status: "live",
    summary: "Moving sources, observers, pitch shifts, and shock cones.",
  },
  {
    id: "hookes-law",
    name: "Hooke's Law Spring",
    discipline: "Physics",
    domain: "Mechanics",
    status: "live",
    summary: "Restoring force, energy, period, damping.",
  },
  {
    id: "projectile-motion",
    name: "Projectile Motion",
    discipline: "Physics",
    domain: "Mechanics",
    status: "live",
    summary: "Launch angle, velocity, range, flight time.",
  },
  {
    id: "pendulum",
    name: "Pendulum",
    discipline: "Physics",
    domain: "Mechanics",
    status: "live",
    summary: "Period, gravity, length, energy exchange.",
  },
  {
    id: "ohms-law",
    name: "Ohm's Law Circuit",
    discipline: "Physics",
    domain: "Electricity",
    status: "live",
    summary: "Voltage, resistance, current, power.",
  },
  {
    id: "rc-circuit",
    name: "RC Circuit Charging",
    discipline: "Physics",
    domain: "Electricity",
    status: "live",
    summary: "Time constant, exponential charging, current decay, and stored energy.",
  },
  {
    id: "wire-magnetic-field",
    name: "Magnetic Field Around A Wire",
    discipline: "Physics",
    domain: "Electricity",
    status: "live",
    summary: "Current direction, circular magnetic field, compass deflection.",
  },
  {
    id: "parallel-plate-capacitor",
    name: "Parallel Plate Capacitor",
    discipline: "Physics",
    domain: "Electricity",
    status: "live",
    summary: "Capacitance, dielectric strength, field, charge, and stored energy.",
  },
  {
    id: "coulombs-law",
    name: "Coulomb's Law",
    discipline: "Physics",
    domain: "Electricity",
    status: "live",
    summary: "Charge signs, inverse-square force, electric field, and potential energy.",
  },
  {
    id: "incline-force",
    name: "Normal Force On Incline",
    discipline: "Physics",
    domain: "Forces",
    status: "live",
    summary: "Weight components, normal force, friction.",
  },
  {
    id: "newtons-second-law",
    name: "Newton's Second Law",
    discipline: "Physics",
    domain: "Forces",
    status: "live",
    summary: "Net force, mass, acceleration, friction, and motion.",
  },
  {
    id: "work-energy",
    name: "Work And Energy",
    discipline: "Physics",
    domain: "Mechanics",
    status: "live",
    summary: "Work, kinetic energy, friction loss, and final speed.",
  },
  {
    id: "snells-law",
    name: "Snell's Law Refraction",
    discipline: "Physics",
    domain: "Optics",
    status: "live",
    summary: "Refraction, critical angle, reflection, and wavelength shift.",
  },
  {
    id: "thin-lens",
    name: "Thin Lens",
    discipline: "Physics",
    domain: "Optics",
    status: "live",
    summary: "Focal length, image distance, magnification, and ray formation.",
  },
  {
    id: "newton-cooling",
    name: "Newton's Law Of Cooling",
    discipline: "Physics",
    domain: "Thermodynamics",
    status: "live",
    summary: "Thermal relaxation, ambient temperature, heat rate, and half-time.",
  },
  {
    id: "carnot-engine",
    name: "Carnot Engine",
    discipline: "Physics",
    domain: "Thermodynamics",
    status: "live",
    summary: "Hot and cold reservoirs, ideal efficiency, work, and rejected heat.",
  },
  {
    id: "buoyancy",
    name: "Buoyancy",
    discipline: "Physics",
    domain: "Fluids",
    status: "live",
    summary: "Density, displaced volume, buoyant force, and floating.",
  },
  {
    id: "hydrostatic-pressure",
    name: "Hydrostatic Pressure",
    discipline: "Physics",
    domain: "Fluids",
    status: "live",
    summary: "Depth, density, gravity, surface pressure, and fluid force.",
  },
  {
    id: "circular-motion",
    name: "Uniform Circular Motion",
    discipline: "Physics",
    domain: "Mechanics",
    status: "live",
    summary: "Radius, angular speed, centripetal acceleration.",
  },
  {
    id: "gravity-field",
    name: "Newtonian Gravity Field",
    discipline: "Physics",
    domain: "Gravity",
    status: "live",
    summary: "Mass, separation, field strength, barycenter, and orbit period.",
  },
  {
    id: "lorenz",
    name: "Lorenz Attractor",
    discipline: "Math",
    domain: "Chaos",
    status: "live",
    summary: "Sensitive dependence and strange attractor geometry.",
  },
  {
    id: "orbital",
    name: "Orbital Mechanics",
    discipline: "Physics",
    domain: "Gravity",
    status: "live",
    summary: "N-body motion, transfer arcs, resonance.",
  },
];
